/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ruge.base.de.datos;


import controladores.PersonasJpaController;
import entidades.Personas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafae
 */
public class tabla_per extends javax.swing.JFrame {

    
    PersonasJpaController perso = new PersonasJpaController();
    public tabla_per() {
        initComponents();
        tabla_per();
        cargar_info_per();
    }
    DefaultTableModel tabla_per;
    
    private void tabla_per() {
        try {
            tabla_per = (new DefaultTableModel(
                    null, new String[]{
                        "Numero documento", "Tipo documento",
                        "Nombre persona","Apellido persona"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                    
                };
                    boolean[] canEdit = new boolean[]{
                    false, false, false,false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            per1.setModel(tabla_per);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }
     private void cargar_info_per() {
        try {
            System.out.println("CARGANDO...");
            
            Object O[] =null;
            List<Personas> ListP = perso.findPersonasEntities();
            
            for (int i =0; i <ListP.size();i++){
                
                tabla_per.addRow(O);
                tabla_per.setValueAt(ListP.get(i).getNumeroDocumento(), i,0);
                tabla_per.setValueAt(ListP.get(i).getTipoDocumento(), i,1);
                tabla_per.setValueAt(ListP.get(i).getNombrePersonas(), i,2);
                tabla_per.setValueAt(ListP.get(i).getApellidoPersonas(), i,3);
            }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    } 

    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbvolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        per1 = new javax.swing.JTable();
        lbfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbvolver.setText("volver");
        jbvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        per1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(per1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 400, 160));

        lbfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/84c7533732d177a41af6612111907d0e.jpg"))); // NOI18N
        getContentPane().add(lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvolverActionPerformed
       consul tabper  = new consul ();
        tabper.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jbvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla_per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabla_per().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbvolver;
    private javax.swing.JLabel lbfondo;
    private javax.swing.JTable per1;
    // End of variables declaration//GEN-END:variables
}
