//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR_VIDEOJUEGO
    {
        public decimal ID_ADMINISTRADOR { get; set; }
        public decimal ID_VIDEOJUEGO { get; set; }
        public decimal ID_ADMINISTRADOR_VIDEOJUEGO { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual VIDEOJUEGO VIDEOJUEGO { get; set; }
    }
}
