/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.base.de.datos;

import controladores.PersonasJpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class reguistro_personas extends javax.swing.JFrame {
    //PersonasJpaController Perso = new PersonasJpaController();
    public reguistro_personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNom = new javax.swing.JLabel();
        lbapellido = new javax.swing.JLabel();
        lbnumdoc = new javax.swing.JLabel();
        lbtidocu = new javax.swing.JLabel();
        jbguardar = new javax.swing.JButton();
        jbvolver = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnumdoc = new javax.swing.JTextField();
        txttipdoc = new javax.swing.JTextField();
        lbtil = new javax.swing.JLabel();
        lbfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNom.setForeground(new java.awt.Color(255, 255, 255));
        lbNom.setText("Nombre");
        getContentPane().add(lbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        lbapellido.setForeground(new java.awt.Color(255, 255, 255));
        lbapellido.setText("Apellido");
        getContentPane().add(lbapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        lbnumdoc.setForeground(new java.awt.Color(255, 255, 255));
        lbnumdoc.setText("Numero documento");
        getContentPane().add(lbnumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        lbtidocu.setForeground(new java.awt.Color(255, 255, 255));
        lbtidocu.setText("Tipo documento");
        getContentPane().add(lbtidocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jbguardar.setText("reguistrar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        jbvolver.setText("volver");
        jbvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 60, 70, 30));
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 70, 30));
        getContentPane().add(txtnumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 180, 70, 30));

        txttipdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipdocActionPerformed(evt);
            }
        });
        getContentPane().add(txttipdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, 30));

        lbtil.setForeground(new java.awt.Color(255, 255, 255));
        lbtil.setText("REGUISTRO PERSONAS");
        getContentPane().add(lbtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lbfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pesas-de-ejercicio-mancuernas-de-hierro-con-placas-extra_1423-223.jpg"))); // NOI18N
        getContentPane().add(lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 546, 414));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttipdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipdocActionPerformed

    private void jbvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvolverActionPerformed
       consul volp  = new consul ();
        volp.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jbvolverActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        String dato1,dato2,dato3,dato4;
        dato1 = txtnombre.getText();
        dato2 = txtapellido.getText();
        dato3 = txtnumdoc.getText();
        dato4 = txttipdoc.getText();
       
        
        JOptionPane.showMessageDialog(null,"reguistro exitoso");
    }//GEN-LAST:event_jbguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reguistro_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reguistro_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reguistro_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reguistro_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reguistro_personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbvolver;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbapellido;
    private javax.swing.JLabel lbfondo;
    private javax.swing.JLabel lbnumdoc;
    private javax.swing.JLabel lbtidocu;
    private javax.swing.JLabel lbtil;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumdoc;
    private javax.swing.JTextField txttipdoc;
    // End of variables declaration//GEN-END:variables
}
