--CREAR LOGIN DEL PROYECTO PARA ACCESO A LA BASE DE DATOS A TRAVÉS DE AUTENTICACIÓN DE SQL SERVER
CREATE LOGIN taller 
    WITH PASSWORD = '291015'
GO

--CREAR BASE DE DATOS DEL PROYECTO
CREATE DATABASE carcenter;
GO

USE carcenter;
GO

--CREAR USUARIO DE BASE DE DATOS PARA EL PROYECTO
CREATE USER carcenterUser
	FOR LOGIN taller
GO

--OTROGAR PERMISO PARA QUE EL USUARIO DE BD DEL PROYECTO TENGA ACCESO A LA BD DEL PROYECTO
EXEC sp_addrolemember 'db_datareader', 'carcenterUser';
GRANT CREATE TABLE TO carcenterUser;
GO

--OTORGAR PERMISOS PARA QUE EL USUARIO DE BD TENGA ACCESO A GESTIONAR OBJETOS EN
--EL ESQUEMA POR DEFECTO DE LA BD (dbo)
GRANT ALTER, CONTROL, CREATE SEQUENCE, DELETE, EXECUTE,
INSERT, REFERENCES, SELECT, TAKE OWNERSHIP, VIEW CHANGE TRACKING, 
VIEW DEFINITION, UPDATE ON SCHEMA :: dbo TO carcenterUser;
GO



