/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operacion;

/**
 *
 * @author Software
 */
public class calcular extends javax.swing.JFrame {

    /**
     * Creates new form calcular
     */
    public calcular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tabla = new javax.swing.JLabel();
        txt_v1 = new javax.swing.JTextField();
        jl_de = new javax.swing.JLabel();
        txt_de_num = new javax.swing.JTextField();
        jl_hasta = new javax.swing.JLabel();
        txt_hasta = new javax.swing.JTextField();
        jb_mostrar_tabla_espe = new javax.swing.JButton();
        jb_mostrar = new javax.swing.JButton();
        jb_nue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_tabla = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_tabla.setText("Mostrar tabla del numero:");
        getContentPane().add(jL_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 20));

        txt_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_v1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 50, -1));

        jl_de.setText("De:");
        getContentPane().add(jl_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 40, 20));
        getContentPane().add(txt_de_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, -1));

        jl_hasta.setText("Hasta:");
        getContentPane().add(jl_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 20));
        getContentPane().add(txt_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 50, -1));

        jb_mostrar_tabla_espe.setText("Mostrar Tabla Especifica");
        jb_mostrar_tabla_espe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mostrar_tabla_espeActionPerformed(evt);
            }
        });
        getContentPane().add(jb_mostrar_tabla_espe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jb_mostrar.setText("Mostrar Tabla");
        jb_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jb_nue.setText("Nuevo");
        jb_nue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nueActionPerformed(evt);
            }
        });
        getContentPane().add(jb_nue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        txa_tabla.setColumns(20);
        txa_tabla.setRows(5);
        jScrollPane1.setViewportView(txa_tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 470, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_v1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_v1ActionPerformed

    private void jb_mostrar_tabla_espeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mostrar_tabla_espeActionPerformed
       int numero=Integer.parseInt(txt_v1.getText());
       //tirulo tabla 
       txa_tabla.append("tabla de multiplicar de: "+numero+"\n");
       for(int i=1;i<=10;i++){
           txa_tabla.append(numero+" x "+i+" = "+numero*i+"\n");
       }
    }//GEN-LAST:event_jb_mostrar_tabla_espeActionPerformed

    private void jb_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mostrarActionPerformed
        int numero=Integer.parseInt(txt_v1.getText());
        int valInicial=Integer.parseInt(txt_de_num.getText());
        int valFinal=Integer.parseInt(txt_hasta.getText());
        //mostrar tirulo resultado
        for(int i=valInicial;i<=valFinal;i++){
            valInicial=numero*i;
            txa_tabla.append(numero+" x "+i+" = "+valInicial+"\n");
        }
        
    }//GEN-LAST:event_jb_mostrarActionPerformed

    private void jb_nueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nueActionPerformed
    txt_v1.setText("");
    txt_de_num.setText("");
    txt_hasta.setText("");
    txa_tabla.setText("");
    }//GEN-LAST:event_jb_nueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_tabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_mostrar;
    private javax.swing.JButton jb_mostrar_tabla_espe;
    private javax.swing.JButton jb_nue;
    private javax.swing.JLabel jl_de;
    private javax.swing.JLabel jl_hasta;
    private javax.swing.JTextArea txa_tabla;
    private javax.swing.JTextField txt_de_num;
    private javax.swing.JTextField txt_hasta;
    private javax.swing.JTextField txt_v1;
    // End of variables declaration//GEN-END:variables
}
